name: Main
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Configure Gradle properties
        run: echo -e "gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}\ngradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" > ~/.gradle/gradle.properties
      - name: Publish Gradle plugin
        run: ./gradlew publishPlugins
